name: Deploy Notes Backend

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP }} > ~/.ssh/known_hosts

      - name: Build JAR
        run: |
          ./gradlew bootJar

      - name: Get JAR Version from build.gradle.kts
        id: get_version
        run: |
          VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' build.gradle.kts)
          echo "JAR_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Deploy JAR to Server
        run: |
          JAR_NAME="spring_boot_crash_course-${{ env.JAR_VERSION }}.jar"
          LOCAL_JAR_PATH="build/libs/$JAR_NAME"
          REMOTE_SERVER="admin@${{ secrets.DEPLOY_SERVER_IP }}"
          REMOTE_JAR_DIR="/opt/notes"
          TIMESTAMP=$(date +%Y%m%d%H%M%S) # Create timestamp
          BACKUP_JAR_NAME="notes_$TIMESTAMP.jar" # Backup name with timestamp
          
          rsync -avz -e "ssh" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/$JAR_NAME

          ssh $REMOTE_SERVER << EOF
            mv $REMOTE_JAR_DIR/notes.jar $REMOTE_JAR_DIR/$BACKUP_JAR_NAME
            cp $REMOTE_JAR_DIR/$JAR_NAME $REMOTE_JAR_DIR/notes.jar
            sudo systemctl restart notes.service
          EOF
